name: Zbuduj aplikacje EXE

on:
  push:
    branches: [ main ]
    paths:
      - 'SpiderHeckManager.py'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Pobierz kod
      uses: actions/checkout@v4

    - name: Przygotuj Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Zainstaluj biblioteki
      run: |
        pip install pyinstaller
        pip install customtkinter

    - name: Kompiluj do EXE
      run: pyinstaller --onefile --noconsole --name SpiderHeckManager SpiderHeckManager.py

    - name: Udostępnij plik EXE
      uses: actions/upload-artifact@v4
      with:
        name: SpiderHeck-ModManager-Windows
        path: dist/SpiderHeckManager.exe
